image:
  repo: mythril/api-probe
  tag: v0.1.0

mongodb:
  url: mongodb://mongodb-replicaset-0.mongodb-replicaset:27017/mythril?replicaSet=mythril-api

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

environment: production
